/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsAdminPanelSettingsOutline: typeof import('~icons/material-symbols/admin-panel-settings-outline')['default']
    IMaterialSymbolsAnalyticsOutline: typeof import('~icons/material-symbols/analytics-outline')['default']
    IMaterialSymbolsArrowBackIosNew: typeof import('~icons/material-symbols/arrow-back-ios-new')['default']
    IMaterialSymbolsArrowDropDown: typeof import('~icons/material-symbols/arrow-drop-down')['default']
    IMaterialSymbolsBookmarkAddedOutline: typeof import('~icons/material-symbols/bookmark-added-outline')['default']
    IMaterialSymbolsBookmarkRemoveOutline: typeof import('~icons/material-symbols/bookmark-remove-outline')['default']
    IMaterialSymbolsCallOutline: typeof import('~icons/material-symbols/call-outline')['default']
    IMaterialSymbolsCampaignOutline: typeof import('~icons/material-symbols/campaign-outline')['default']
    IMaterialSymbolsChatBubbleOutline: typeof import('~icons/material-symbols/chat-bubble-outline')['default']
    IMaterialSymbolsChatOutline: typeof import('~icons/material-symbols/chat-outline')['default']
    IMaterialSymbolsCheckCircle: typeof import('~icons/material-symbols/check-circle')['default']
    IMaterialSymbolsCheckCircleOutline: typeof import('~icons/material-symbols/check-circle-outline')['default']
    IMaterialSymbolsChevronLeft: typeof import('~icons/material-symbols/chevron-left')['default']
    IMaterialSymbolsChevronRight: typeof import('~icons/material-symbols/chevron-right')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsDeleteOutline: typeof import('~icons/material-symbols/delete-outline')['default']
    IMaterialSymbolsDescriptionOutline: typeof import('~icons/material-symbols/description-outline')['default']
    IMaterialSymbolsDirectionsCarOutline: typeof import('~icons/material-symbols/directions-car-outline')['default']
    IMaterialSymbolsDiversity3: typeof import('~icons/material-symbols/diversity3')['default']
    IMaterialSymbolsEditNoteOutline: typeof import('~icons/material-symbols/edit-note-outline')['default']
    IMaterialSymbolsEditOutline: typeof import('~icons/material-symbols/edit-outline')['default']
    IMaterialSymbolsEditSquareOutline: typeof import('~icons/material-symbols/edit-square-outline')['default']
    IMaterialSymbolsErrorOutline: typeof import('~icons/material-symbols/error-outline')['default']
    IMaterialSymbolsExpandMore: typeof import('~icons/material-symbols/expand-more')['default']
    IMaterialSymbolsFavoriteOutline: typeof import('~icons/material-symbols/favorite-outline')['default']
    IMaterialSymbolsForumOutline: typeof import('~icons/material-symbols/forum-outline')['default']
    IMaterialSymbolsHandshakeOutline: typeof import('~icons/material-symbols/handshake-outline')['default']
    IMaterialSymbolsHomeOutline: typeof import('~icons/material-symbols/home-outline')['default']
    IMaterialSymbolsImageOutline: typeof import('~icons/material-symbols/image-outline')['default']
    IMaterialSymbolsInfoOutline: typeof import('~icons/material-symbols/info-outline')['default']
    IMaterialSymbolsListAltOutline: typeof import('~icons/material-symbols/list-alt-outline')['default']
    IMaterialSymbolsLocalParking: typeof import('~icons/material-symbols/local-parking')['default']
    IMaterialSymbolsLocationOnOutline: typeof import('~icons/material-symbols/location-on-outline')['default']
    IMaterialSymbolsLockOutline: typeof import('~icons/material-symbols/lock-outline')['default']
    IMaterialSymbolsLockReset: typeof import('~icons/material-symbols/lock-reset')['default']
    IMaterialSymbolsLogout: typeof import('~icons/material-symbols/logout')['default']
    IMaterialSymbolsMailOutline: typeof import('~icons/material-symbols/mail-outline')['default']
    IMaterialSymbolsMarkEmailReadOutline: typeof import('~icons/material-symbols/mark-email-read-outline')['default']
    IMaterialSymbolsMyLocationOutline: typeof import('~icons/material-symbols/my-location-outline')['default']
    IMaterialSymbolsNotificationsActiveOutline: typeof import('~icons/material-symbols/notifications-active-outline')['default']
    IMaterialSymbolsPersonAddOutline: typeof import('~icons/material-symbols/person-add-outline')['default']
    IMaterialSymbolsPersonOutline: typeof import('~icons/material-symbols/person-outline')['default']
    IMaterialSymbolsPostAdd: typeof import('~icons/material-symbols/post-add')['default']
    IMaterialSymbolsRadioButtonUnchecked: typeof import('~icons/material-symbols/radio-button-unchecked')['default']
    IMaterialSymbolsRateReviewOutline: typeof import('~icons/material-symbols/rate-review-outline')['default']
    IMaterialSymbolsReceiptLongOutline: typeof import('~icons/material-symbols/receipt-long-outline')['default']
    IMaterialSymbolsScheduleOutline: typeof import('~icons/material-symbols/schedule-outline')['default']
    IMaterialSymbolsSearch: typeof import('~icons/material-symbols/search')['default']
    IMaterialSymbolsShoppingBagOutline: typeof import('~icons/material-symbols/shopping-bag-outline')['default']
    IMaterialSymbolsStarOutline: typeof import('~icons/material-symbols/star-outline')['default']
    IMaterialSymbolsStorefrontOutline: typeof import('~icons/material-symbols/storefront-outline')['default']
    IMaterialSymbolsThumbUpOutline: typeof import('~icons/material-symbols/thumb-up-outline')['default']
    IMaterialSymbolsVerifiedOutline: typeof import('~icons/material-symbols/verified-outline')['default']
    IMaterialSymbolsVisibilityOutline: typeof import('~icons/material-symbols/visibility-outline')['default']
    IMaterialSymbolsWarningOutline: typeof import('~icons/material-symbols/warning-outline')['default']
    ParkingCalculator: typeof import('./src/components/ParkingCalculator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
